// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu8H64O0m1q0kTt85djED7K6Xq_KJJs5I',
    appId: '1:399602322284:web:98e66c2688ef9337928149',
    messagingSenderId: '399602322284',
    projectId: 'fir-auth-f49a7',
    authDomain: 'fir-auth-f49a7.firebaseapp.com',
    storageBucket: 'fir-auth-f49a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUKYxEOsGbXi7nGCDVU_dSscHDyiau7gk',
    appId: '1:399602322284:android:df81bb7a28efa28d928149',
    messagingSenderId: '399602322284',
    projectId: 'fir-auth-f49a7',
    storageBucket: 'fir-auth-f49a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ6fhdRIEp-QpQ5YvUAl3lMl4ybwY_GG0',
    appId: '1:399602322284:ios:af9ad77f73bfd1b5928149',
    messagingSenderId: '399602322284',
    projectId: 'fir-auth-f49a7',
    storageBucket: 'fir-auth-f49a7.appspot.com',
    iosBundleId: 'com.example.firebaseAuthBloc',
  );
}
